package vut;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 * Guess the number game
 * Date Started 20/11/2024
 * @author Teboho
 */
public class MainForm extends javax.swing.JFrame {

    private int attempts;
    private final int maxAttempts = 5;
    private final int min = 1;
    private final int max = 100;
    private final int randomNumber = (int) (Math.random() * (max - min + 1) + min);
    private int rounds = 1;
    private int score = 0;
    private int round = 1;

    private ArrayList<Integer> numbers = new ArrayList<Integer>();

    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        lblMessage = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtNumber = new javax.swing.JTextField();
        btnSubmit = new javax.swing.JButton();
        btnPlayAgain = new javax.swing.JButton();
        btnShowResults = new javax.swing.JButton();
        btnRestart = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        btnViewScore = new javax.swing.JButton();
        lblScoreBoard = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        lblNumber1 = new javax.swing.JLabel();
        lblResults = new javax.swing.JLabel();
        lblNumber2 = new javax.swing.JLabel();
        lblNumber3 = new javax.swing.JLabel();
        lblNumber4 = new javax.swing.JLabel();
        lblNumber5 = new javax.swing.JLabel();
        lblViewScore = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lblNumber6 = new javax.swing.JLabel();
        lblNumber7 = new javax.swing.JLabel();
        lblNumber8 = new javax.swing.JLabel();
        lblNumber9 = new javax.swing.JLabel();
        lblNumber10 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("GUESS THE NUMBER"));

        jLabel2.setText("Welcome to Guess the Number Game!");

        jLabel1.setText("I have selected a number between 1 and 100.");

        lblMessage.setText("You have 5 attempts to guess the number.");
        lblMessage.addAncestorListener(new javax.swing.event.AncestorListener() {
            public void ancestorAdded(javax.swing.event.AncestorEvent evt) {
                lblMessageAncestorAdded(evt);
            }
            public void ancestorMoved(javax.swing.event.AncestorEvent evt) {
            }
            public void ancestorRemoved(javax.swing.event.AncestorEvent evt) {
            }
        });

        jLabel4.setText("Enter your number: ");

        btnSubmit.setText("Submit");
        btnSubmit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSubmitActionPerformed(evt);
            }
        });

        btnPlayAgain.setText("Play Again");
        btnPlayAgain.setEnabled(false);
        btnPlayAgain.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPlayAgainActionPerformed(evt);
            }
        });

        btnShowResults.setText("Show Results");
        btnShowResults.setEnabled(false);
        btnShowResults.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnShowResultsActionPerformed(evt);
            }
        });

        btnRestart.setText("Restart");
        btnRestart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRestartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblMessage)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(114, 114, 114)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnPlayAgain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap())
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addComponent(btnSubmit)
                            .addGap(27, 27, 27))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(btnShowResults, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addContainerGap()))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnRestart)
                        .addGap(24, 24, 24))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblMessage)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txtNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(btnSubmit)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnPlayAgain)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnShowResults)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnRestart)
                        .addContainerGap())))
        );

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Score board"));

        btnViewScore.setText("View Score");
        btnViewScore.setEnabled(false);
        btnViewScore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewScoreActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblScoreBoard, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(98, 98, 98)
                        .addComponent(btnViewScore)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblScoreBoard)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 147, Short.MAX_VALUE)
                .addComponent(btnViewScore)
                .addContainerGap())
        );

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Results"));

        lblNumber1.setBackground(new java.awt.Color(0, 0, 0));

        lblResults.setBackground(new java.awt.Color(0, 0, 0));

        lblNumber2.setBackground(new java.awt.Color(0, 0, 0));

        lblNumber3.setBackground(new java.awt.Color(0, 0, 0));

        lblNumber4.setBackground(new java.awt.Color(0, 0, 0));

        lblNumber5.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblNumber1, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblResults, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber2, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber3, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber4, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblNumber5, javax.swing.GroupLayout.PREFERRED_SIZE, 347, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViewScore, javax.swing.GroupLayout.PREFERRED_SIZE, 413, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(lblResults)
                .addGap(14, 14, 14)
                .addComponent(lblNumber1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumber2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumber3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumber4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblNumber5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblViewScore)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Round 2"));

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(lblNumber9, javax.swing.GroupLayout.DEFAULT_SIZE, 143, Short.MAX_VALUE)
                        .addComponent(lblNumber8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumber7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblNumber6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(lblNumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(98, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(lblNumber6, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumber7, javax.swing.GroupLayout.PREFERRED_SIZE, 12, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumber8, javax.swing.GroupLayout.PREFERRED_SIZE, 11, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumber9, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblNumber10, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(69, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSubmitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSubmitActionPerformed

       
        String userGuess = txtNumber.getText();

        if (userGuess.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Error: Please enter a number.",
                    "Invalid Input", JOptionPane.ERROR_MESSAGE);

        } else {
            attempts++;

            try {

                int guess = Integer.parseInt(userGuess);

                if (guess == randomNumber) {
                    lblMessage.setText("Congratulations! You guessed the number in " + attempts + " attempts.");
                    JOptionPane.showMessageDialog(null, "Congratulations! You guessed the number in " + attempts + " attempts.",
                            "Congratulation", JOptionPane.DEFAULT_OPTION);

                    score = 1;
                    end();
                    
                } else if (guess < randomNumber) {
                    lblMessage.setText("You have " + (maxAttempts - attempts) + " attempts remaining.");
                    JOptionPane.showMessageDialog(null, "Too low! " + (maxAttempts - attempts) + " attempts remaining.",
                            "Value too low", JOptionPane.ERROR_MESSAGE);

                } else {
                    lblMessage.setText("You have " + (maxAttempts - attempts) + " attempts remaining.");
                    JOptionPane.showMessageDialog(null, "Too high! " + (maxAttempts - attempts) + " attempts remaining.",
                            "Value too high", JOptionPane.ERROR_MESSAGE);

                }

                if (attempts >= maxAttempts && round == 2 ) {
                    lblMessage.setText("Out of attempts! Play again");
                    end();
                } else if (attempts >= maxAttempts){
                    lblMessage.setText("Out of attempts! Play again");
                    endGame();
                    
                }
             

                numbers.add(guess);
                txtNumber.setText("");

            } catch (NumberFormatException ex) {
                JOptionPane.showMessageDialog(null, "Error: Please enter a valid number.",
                        "Invalid Input", JOptionPane.ERROR_MESSAGE);

            }

        }

    }//GEN-LAST:event_btnSubmitActionPerformed

    private void btnViewScoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewScoreActionPerformed

        if (score == 1) {

            lblScoreBoard.setText("Your got " + score + " out of 1");

        } else {
            lblScoreBoard.setText("You got " + score + " out of 1. "
                    + "Resert the game.");
        }
    }//GEN-LAST:event_btnViewScoreActionPerformed

    private void lblMessageAncestorAdded(javax.swing.event.AncestorEvent evt) {//GEN-FIRST:event_lblMessageAncestorAdded
        lblMessage.setText("You have " + maxAttempts + " attempts remaining.");
    }//GEN-LAST:event_lblMessageAncestorAdded

    private void btnPlayAgainActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPlayAgainActionPerformed
        resetGame();
        rounds++;
        
    }//GEN-LAST:event_btnPlayAgainActionPerformed

    private void btnShowResultsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnShowResultsActionPerformed

        lblMessage.setText("");
        lblResults.setText("You have played " + rounds + " rounds.");

        if (numbers.get(0) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));

        } else if (numbers.get(1) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));

        } else if (numbers.get(2) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));

        } else if (numbers.get(3) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));

        } else if (numbers.get(4) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));

        }  
        
        else if (numbers.get(5) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));

        } else if (numbers.get(6) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));
            lblNumber7.setText("The 7th number: " + numbers.get(6));

        } else if (numbers.get(7) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));
            lblNumber7.setText("The 7th number: " + numbers.get(6));
            lblNumber8.setText("The 8th number: " + numbers.get(7));

        } else if (numbers.get(8) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));
            lblNumber7.setText("The 7th number: " + numbers.get(6));
            lblNumber8.setText("The 8th number: " + numbers.get(7));
            lblNumber9.setText("The 9th number: " + numbers.get(8));

        } else if (numbers.get(9) == randomNumber) {

            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));
            lblNumber7.setText("The 7th number: " + numbers.get(6));
            lblNumber8.setText("The 8th number: " + numbers.get(7));
            lblNumber9.setText("The 9th number: " + numbers.get(8));
            lblNumber10.setText("The 10th number: " + numbers.get(9));
            
            
        } else {
            lblNumber1.setText("The first number: " + numbers.get(0));
            lblNumber2.setText("The second number: " + numbers.get(1));
            lblNumber3.setText("The third number: " + numbers.get(2));
            lblNumber4.setText("The fourth number: " + numbers.get(3));
            lblNumber5.setText("The fith number: " + numbers.get(4));
            lblNumber6.setText("The 6th number: " + numbers.get(5));
            lblNumber7.setText("The 7th number: " + numbers.get(6));
            lblNumber8.setText("The 8th number: " + numbers.get(7));
            lblNumber9.setText("The 9th number: " + numbers.get(8));
            lblNumber10.setText("The 10th number: " + numbers.get(9));
        }

        lblViewScore.setText("The number you are looking for is: "
                + randomNumber);

        end();
        btnViewScore.setEnabled(true);

    }//GEN-LAST:event_btnShowResultsActionPerformed

    private void btnRestartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRestartActionPerformed
       
        newGame();
        
    }//GEN-LAST:event_btnRestartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnPlayAgain;
    private javax.swing.JButton btnRestart;
    private javax.swing.JButton btnShowResults;
    private javax.swing.JButton btnSubmit;
    private javax.swing.JButton btnViewScore;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblMessage;
    private javax.swing.JLabel lblNumber1;
    private javax.swing.JLabel lblNumber10;
    private javax.swing.JLabel lblNumber2;
    private javax.swing.JLabel lblNumber3;
    private javax.swing.JLabel lblNumber4;
    private javax.swing.JLabel lblNumber5;
    private javax.swing.JLabel lblNumber6;
    private javax.swing.JLabel lblNumber7;
    private javax.swing.JLabel lblNumber8;
    private javax.swing.JLabel lblNumber9;
    private javax.swing.JLabel lblResults;
    private javax.swing.JLabel lblScoreBoard;
    private javax.swing.JLabel lblViewScore;
    private javax.swing.JTextField txtNumber;
    // End of variables declaration//GEN-END:variables

    private void endGame() {
        btnSubmit.setEnabled(false);
        btnPlayAgain.setEnabled(true);
        btnShowResults.setEnabled(false);
    }

    private void end() {
        btnSubmit.setEnabled(false);
        btnPlayAgain.setEnabled(false);
        btnShowResults.setEnabled(true);
    }
    
    private void newGame(){
        attempts = 0;
        round = 0;
        numbers.clear();
        clearLabel();
        btnShowResults.setEnabled(false);
        btnViewScore.setEnabled(false);
        
        if (lblMessage != null) {
            lblMessage.setText("You have " + maxAttempts + " attempts remaining.");
        }
        if (txtNumber != null) {
            txtNumber.setText("");
        }
        if (btnSubmit != null) {
            btnSubmit.setEnabled(true);
        }
        if (btnPlayAgain != null) {
            btnPlayAgain.setEnabled(false);
        }
        
    
        
    }
    private void resetGame() {

        attempts = 0;
        round = 2;
        
        if (lblMessage != null) {
            lblMessage.setText("You have " + maxAttempts + " attempts remaining.");
        }
        if (txtNumber != null) {
            txtNumber.setText("");
        }
        if (btnSubmit != null) {
            btnSubmit.setEnabled(true);
        }
        if (btnPlayAgain != null) {
            btnPlayAgain.setEnabled(false);
        }
    }
    
    private void clearLabel() {

        lblNumber1.setText("");
        lblNumber2.setText("");
        lblNumber3.setText("");
        lblNumber4.setText("");
        lblNumber5.setText("");
        lblNumber6.setText("");
        lblNumber7.setText("");
        lblNumber8.setText("");
        lblNumber9.setText("");
        lblNumber10.setText("");
        lblViewScore.setText("");
        lblResults.setText("");
        lblScoreBoard.setText("");

    }
}
